### ISSUE TITLE
cannot edit documents

### ISSUE THREAD

**Issue by billie66** [andzdroid/mongo-express#108]
My mongodb version is 3.0.6.

After installed mongo-express, I started it and logged in successfully, but i got the following web interface

![screen shot 2015-10-07 at 10 53 26 pm](https://cloud.githubusercontent.com/assets/102444/10341199/55602e4a-6d46-11e5-9312-835c83b60b35.png)

As shown in the image above,  there are no buttons to edit documents,  so I can not delete/create documents.

**Comment by wulfsolter** [comment]
Click on one of the documents shown (dark blue boxes)

**Comment by billie66** [comment]
@wulfsolter  Thanks for your reply.

Clicked one of the documents after, i got the page blow

![screen shot 2015-10-08 at 9 41 54 am](https://cloud.githubusercontent.com/assets/102444/10355630/e9009f68-6da0-11e5-892e-d7587f346213.png)


There are still no red delete button on the right side of the document, and it can not be edited

Actually, the mongo-express worked normally before it was reinstalled with the latest version, its control panel was exactly like the image shown in the mongo-express readme file, but now it doesn't work.

**Comment by wulfsolter** [comment]
Are there errors in the consoles? Both from the browser and node consoles.
What version are you running (as listed in your package.json)? Where are you installing it from?

**Comment by billie66** [comment]
There are no errors in both place. 

My mongo-express version is v0.23.2,  node version v0.12.7

I installed mongo-express in my home directory, not globally installed

```
npm install mongo-express
```

after installed it,  entered `~/node_modules/mongo-express` directory, i did a little change with config.js file, using port 3001 instead of 27071

```
port: process.env.ME_CONFIG_MONGODB_PORT || 3001,
```

then ran mongo-express with command `node app.js`,  access the url `localhost:8081`, enter the username `admin` and password `pass` to login

so is there something wrong with the process?  I am really new to mongodb, should i do some work with mongodb?

**Comment by wulfsolter** [comment]
Do you have the readOnly flag in your config set to true?

    //readOnly: if readOnly is true, components of writing are not visible.
    readOnly: true

**Comment by billie66** [comment]
changed readOnly to false, it works!

@wulfsolter Thank you very much, you are perfect!
