### ISSUE TITLE
no delete option.

### ISSUE THREAD

**Issue by sathishstar** [andzdroid/mongo-express#112]
I am using ubuntu 14.04. i installed mongo express using, 

sudo npm install mongo-express.

then i installed npm install inside the mongo-express folder. after I opened my mongo-expres . IN collection there is no delete option for the data.

![screenshot from 2015-10-16 16 46 08](https://cloud.githubusercontent.com/assets/14369878/10540428/72f70844-7425-11e5-8987-72e686509d93.png)

**Comment by wulfsolter** [comment]
Check your config for being set to read only

**Comment by artzstudio** [comment]
I was also wondering what was up with this, for me it was just that the table was cut off and I had to horizontally scroll.  SMH.

**Comment by wulfsolter** [comment]
Thanks @artzstudio . Latest version now has the delete button as part of the `_id` field on the very first column.

If scrolling sideways was not immediately obvious, I'd love to hear thoughts on how we could make the UI/UX better :)

**Comment by artz** [comment]
If I had a good suggestion I would have left it.  :)  I was thinking perhaps you could indicate there is more by fading out the right side with a drop shadow effect.  Other ideas: http://ux.stackexchange.com/questions/26214/how-to-indicate-container-is-scrollable-without-scroll-bars

**Comment by artz** [comment]
Oh, I'd also recommend putting a delete button on the document view itself.  You had me digging through the source code checking if I wasn't going nuts.  :)

**Comment by wulfsolter** [comment]
Thanks for the link @artz :)

I've added a delete in the document view itself, moved the collection view delete buttons into the leftmost _id column, added a fade-to-white gradient if the table is wider than screen and pushed to npm.

After a lot of UI/UX digging, that's about as good as it gets.... in a world where everyone is **finally** getting the hang of vertical scroll (thanks to touch screen phones!), horizontal table scroll is still a hurdle. If anyone comes across this thread, I'm always open for more insights :)

**Comment by artz** [comment]
You rock, thanks!
