### ISSUE TITLE
TypeError: Cannot read property 'databases' of undefined

### ISSUE THREAD

**Issue by DonRichards** [andzdroid/mongo-express#113]
Not Sure if I'm configuring correctly. Can't connect to remote Mongo server. Here's my config
What am I missing? Thanks!
...
var url = require('url');
if (typeof process.env.MONGODB_PORT === 'string') {
	var mongoConnection = url.parse(process.env.MONGODB_PORT);
	process.env.ME_CONFIG_MONGODB_SERVER = mongoConnection.hostname;
	process.env.ME_CONFIG_MONGODB_PORT = mongoConnection.port;
}
module.exports = {
  mongodb: {
    server: '23.2.2.2' || 'localhost',
    port: process.env.ME_CONFIG_MONGODB_PORT || 27017,
    autoReconnect: true,
    poolSize: 4,
    admin: false,
    auth: [
      {
        database: 'userdb',
        username: 'MyUserName',
        password: 'SuperDuperPassword'
      }
    ],
    adminUsername: process.env.ME_CONFIG_MONGODB_ADMINUSERNAME || '',
    adminPassword: process.env.ME_CONFIG_MONGODB_ADMINPASSWORD || '',
    whitelist: [],
    blacklist: []
  },
  site: {
    host: '0.0.0.0',
    port: 8081,
    cookieSecret: process.env.ME_CONFIG_SITE_COOKIESECRET || 'cookiesecret',
    sessionSecret: process.env.ME_CONFIG_SITE_SESSIONSECRET || 'sessionsecret',
    cookieKeyName: 'mongo-express'
  },
  useBasicAuth: process.env.ME_CONFIG_BASICAUTH_USERNAME != 'true',
  basicAuth: {
    username: process.env.ME_CONFIG_BASICAUTH_USERNAME || 'admin',
    password: process.env.ME_CONFIG_BASICAUTH_PASSWORD || 'pass'
  },

  options: {
    documentsPerPage: 10,
    editorTheme: process.env.ME_CONFIG_OPTIONS_EDITORTHEME || 'rubyblue',
    cmdType: 'eval',
    subprocessTimeout: 300,
    readOnly: true
  }
};
...

**Comment by wulfsolter** [comment]
You made a fix? PR?

**Comment by wulfsolter** [comment]
Cheers for the PR!

**Comment by DonRichards** [comment]
Thanks!!
