### ISSUE TITLE
partial search of text fields

### ISSUE THREAD

**Issue by RafiFeroze** [andzdroid/mongo-express#116]
How do I do a 'like' search on a string field. 
Something like select * from users where name like '%mxse%'

On command line, the following works   db.users.find("name" : /mxse/ )

But when I try this on web front-end, it does not fetch any records

**Comment by wulfsolter** [comment]
It works just fine :)

<img width="553" alt="screen shot 2015-11-06 at 9 18 54 am" src="https://cloud.githubusercontent.com/assets/1692132/10980552/7004540a-8467-11e5-8144-a6004bf80d51.png">
