### ISSUE TITLE
Can't edit/delete documents or execute a query

### ISSUE THREAD

**Issue by nikolaydyankov** [andzdroid/mongo-express#124]
I'm a relatively new user to MongoDB and mongo-express, so forgive my basic question.

A couple of problems:
- I don't see any X button to delete a document. As I understand from the docs and other issues, there should be such a button
- I can't execute any query. I'm getting the "Query entered is not valid" error message. I tried with "db.getCollection('authors').find({})" for example.

In the "config.js" file I have specified "ME_CONFIG_MONGODB_ADMINUSERNAME" and pass. I also tried leaving the admin user/pass fields empty and specifying a "regular" account, but when I start app.js it still says in the console "Admin Database connected", even though I have specified another database.

Please help me set this up properly, I don't know what I'm doing wrong!
Cheers

**Comment by wulfsolter** [comment]
Hi @nikolaydyankov 

I've recently changed the default config to be "readOnly: false", this caught quite a few people off guard who didn't read the whole lot line by line. That should enable delete/edit functionality.

For your second problem, the "advanced" search is simply a mapping into [Mongo's db.collection.find()](https://docs.mongodb.org/manual/reference/method/db.collection.find/) with the left "Query" field being where you would enter Query Operators such as your posted "{}" and the right "Fields" where you enter Projection Operators.

Hope that helps :)
