### ISSUE TITLE
Admin mode, but cannot edit or delete

### ISSUE THREAD

**Issue by jonnycraze** [andzdroid/mongo-express#127]
Please help, I recently updated my mongo-express version. I love this GUI and have gotten to rely on it for quickly editing my data. 

However after the update my admin rights no longer work, i can view collections and data, but there are no options to edit/delete entries.

I have mongodb.admin set to true.

I have the adminUsername and adminPassword setup and it does not throw an error.

Any help would be very very appreciated

**Comment by wulfsolter** [comment]
set readOnly to false or update to latest
