### ISSUE TITLE
Hash-signs in document names are not properly url-encoded

### ISSUE THREAD

**Issue by oloflarsson** [andzdroid/mongo-express#13]
I have a collection. In that collection there is a document called "rank#2"

Searching for it works fine:
http://localhost:8081/db/mstore/massiveperms_thing?key=_id&value=%23rank2
Note that the hash-sign is encoded to %23.

When I click it and try to open it does however not work:
http://localhost:8081/db/mstore/massiveperms_thing/#rank2

And if I manually enter
http://localhost:8081/db/mstore/massiveperms_thing/%23rank2
And edit and save I get the error "You forgot to enter a collection name!"

**Comment by YvesMerl** [comment]
There is a general lack of URL encoding on all dynamic links.
Document ID with special URL characters will not be able to be opened, saved and deleted.

**Comment by YvesMerl** [comment]
I made a pull request: https://github.com/andzdroid/mongo-express/pull/66
