### ISSUE TITLE
Authorization Required

### ISSUE THREAD

**Issue by hfuccillo** [andzdroid/mongo-express#130]
Hi, I'm new with MongoDB and I tried to install mongo-express in an EC2 instance of Amazon.
But when I try to connect to the site, I get a authorization windows saying that I have to put username and password. So the question is: Where I set the user and password in mongo-express to grant access.
Thanks in advance!

**Comment by wulfsolter** [comment]
https://github.com/andzdroid/mongo-express/blob/master/config.default.js#L67-L70

**Comment by wulfsolter** [comment]
To configure:

Copy YOUR_PATH/node_modules/mongo-express/config.default.js into a new file called YOUR_PATH/node_modules/mongo-express/config.js.


https://github.com/andzdroid/mongo-express/blob/master/config.default.js#L67-L70

**Comment by hfuccillo** [comment]
It works!! Thanks @wulfsolter !!!

**Comment by lexaurin** [comment]
@wulfsolter Why are you complicating installation? Mongo is shipped by default without authorization so why can't mongo-express do the same? 

![Why]
(http://i3.kym-cdn.com/entries/icons/square/000/012/189/d7c.gif)

**Comment by wulfsolter** [comment]
@lexaurin You are more than welcome to turn it off, but please don't hijack other threads with annoying GIFs.

While many of the "new" generation NoSQL databases choose not to implement even the most basic security, there are almost as many idiots who don't read configuration files. According to some reports there are 30,000+ MongoDB instances exposed to the public web, a number I would prefer not to increase.
