### ISSUE TITLE
Command line arguments aren't passed to module

### ISSUE THREAD

**Issue by Neta-Alon** [andzdroid/mongo-express#134]
I've installed `mongo-express` globally without any issues. Version is 0.27.2.
My `node version` is 5.0.0 and `npm` is 3.4.1.

The following line: `mongo-express -u MY_ADMIN_USERNAME -p MY_ADMIN_PASSWORD` did not authenticate successfully itself with MongoDB.
I checked the MongoDB log and did some research, and found out that the module simply doesn't search the arguments given to it by the command line.

In `config.js`:
`````javascript
adminUsername: process.env.ME_CONFIG_MONGODB_ADMINUSERNAME || '',
adminPassword: process.env.ME_CONFIG_MONGODB_ADMINPASSWORD || '',
`````

The module searches `process.env`. I found my arguments instead in `process.argv`, and there doesn't seem to be anything that searches the `process.argv` to transfer things to `process.env`. The module simply runs without taking notice what's in the arguments list.

For example: `mongo-express --version` ran the module as if I ran `mongo-express`.

What's not working for me? Where should I look? What's supposed to map the arguments list to the environment variables?

Thanks for any help regarding the issue.

**Comment by wulfsolter** [comment]
@ambrosechua's made some awesome improvements in the last 11 days, so try removing and reinstalling? 0.27.3 is latest version while 'commander' is the CLI interface package, most of the related code sits here: https://github.com/andzdroid/mongo-express/commit/37e76b90f8eabe0321a085c6a4914849efdba1d5
