### ISSUE TITLE
Can't set base url

### ISSUE THREAD

**Issue by pbespechnyi** [andzdroid/mongo-express#135]
I use `knickers/mongo-express:latest` to get instance of mongo-express up and running. But the problem is that I use nginx in front of it and map route to `/mongoexpress/`.

I tried to set `baseUrl` in `site.baseUrl` of my `config.js` as said in README, but this didn't help.

**Comment by wulfsolter** [comment]
Sounds like your nginx reverse proxy config could use a bit of work. Something like?

```
proxy_redirect                off;
proxy_set_header              Host             $host;
proxy_set_header              Port             $server_port;
proxy_set_header              X-Real-IP        $remote_addr;
proxy_set_header              X-Forwarded-For  $proxy_add_x_forwarded_for;
proxy_set_header              X-NginX-Proxy    true;
proxy_pass_request_headers    on;
```

More details at https://www.nginx.com/resources/admin-guide/reverse-proxy/
