### ISSUE TITLE
entities too large, allowable entity size not configurable

### ISSUE THREAD

**Issue by nchase** [andzdroid/mongo-express#142]
this is an awesome tool. lots of mongo payloads are going to be larger than the `body-parser` default of 100KB.

a savvy user can reach in and change the code to update the limit, but there should be a piece of configuration that lets mongo-express users do it through a conventional interface.

pull request coming soon if I can keep my mind here in the same thread :)

**Comment by wulfsolter** [comment]
Thanks for the PR!
