### ISSUE TITLE
Cannot edit documents with numeral _ids

### ISSUE THREAD

**Issue by RashadSaleh** [andzdroid/mongo-express#145]
Try to insert a document with a numeral _id (that is, an _id like "1234" [all numbers]), and editing will fail and return "Document not found!".

**Comment by RashadSaleh** [comment]
Same if the _id is an object...

**Comment by wulfsolter** [comment]
PRs welcome :)

**Comment by wulfsolter** [comment]
Fixed with https://github.com/andzdroid/mongo-express/commit/b89ebb8e6b6d848a009564a2d90055f9dd09b44b

**Comment by RashadSaleh** [comment]
Thanks for the quick fix!
