### ISSUE TITLE
Hosting mongo-express in a subdirectory

### ISSUE THREAD

**Issue by Hubro** [andzdroid/mongo-express#146]
I want to host mongo-express in a subdirectory of my website, e.g.:

    http://www.example.com/mongo-express/

Setting up a reverse proxy using nginx doesn't work, because the mongo-express application requests its style sheets and such from `/`. Setting `config.site.baseUrl` made no difference in that regard.

Is it currently possible to host mongo-express in a subdirectory using the `mongo-express` command? If not, it should be.

**Comment by wulfsolter** [comment]
I've had mongo-express running in a subdir in the past, you're on the right path with `config.site.baseUrl` and reverse proxy.

I had a quick play, and I noticed there was a hardcoded '/' in the main `app.js` startup - https://github.com/andzdroid/mongo-express/commit/44dfff2c5a59ad756e2d6bc6fe29c64c849adac3 - that could've been causing the issue.

**Comment by Hubro** [comment]
Neat, you got it. Installed from git and it works now. On an unrelated note, I got a build error when installing:

```
root@my-pc:~# npm install -g git+https://github.com/andzdroid/mongo-express.git
-
> kerberos@0.0.17 install /usr/local/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/usr/local/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.h:9:0,
                 from ../lib/kerberos.cc:1:
../node_modules/nan/nan.h:316:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
kerberos.target.mk:88: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
/usr/local/bin/mongo-express -> /usr/local/lib/node_modules/mongo-express/app.js
mongo-express@0.27.8 /usr/local/lib/node_modules/mongo-express
├── basic-auth-connect@1.0.0
├── async@1.4.2
├── consolidate@0.12.1
├── underscore@1.8.3
├── cookie-parser@1.4.0 (cookie-signature@1.0.6, cookie@0.2.2)
├── serve-favicon@2.3.0 (fresh@0.3.0, ms@0.7.1, etag@1.7.0, parseurl@1.3.0)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── method-override@2.3.5 (methods@1.1.1, vary@1.0.1, parseurl@1.3.0, debug@2.2.0)
├── express-session@1.11.3 (cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, on-headers@1.0.1, parseurl@1.3.0, depd@1.0.1, crc@3.3.0, uid-safe@2.0.0, debug@2.2.0)
├── morgan@1.6.1 (on-headers@1.0.1, basic-auth@1.0.3, depd@1.0.1, on-finished@2.3.0, debug@2.2.0)
├── errorhandler@1.4.2 (escape-html@1.0.2, accepts@1.2.13)
├── body-parser@1.14.0 (bytes@2.1.0, content-type@1.0.1, depd@1.1.0, http-errors@1.3.1, on-finished@2.3.0, qs@5.1.0, debug@2.2.0, iconv-lite@0.4.11, raw-body@2.1.5, type-is@1.6.10)
├── express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.3, vary@1.0.1, path-to-regexp@0.1.7, content-type@1.0.1, etag@1.7.0, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, on-finished@2.3.0, finalhandler@0.4.0, qs@4.0.0, send@0.13.0, proxy-addr@1.0.10, debug@2.2.0, type-is@1.6.10, accepts@1.2.13)
├── swig@1.4.2 (optimist@0.6.1, uglify-js@2.4.24)
└── mongodb@2.0.43 (readable-stream@1.0.31, es6-promise@2.1.1, mongodb-core@1.2.12)
```

Still, it both succeeds to install and appears to work.

**Comment by wulfsolter** [comment]
Ah, Kerberos is no end of headaches... If you've never had to deal with it, don't even look down that path and enjoy the sunshine and happiness found everywhere else in this world :)

Mongo can do Kerberos auth, hence it's a required module, but I've seen gyp fail more times than I can remember...

From the MongoDB guide: 
```However don’t worry. You only need the kerberos module if intend to use kerberos.```
https://mongodb.github.io/node-mongodb-native/2.0/getting-started/installation-guide/#troubleshooting

**Comment by Hubro** [comment]
Thanks for the warning :)

**Comment by joshperry** [comment]
Is it possible to expose the baseURL config value via an ENV? I'd like to expose this app on my kubernetes cluster and it is much much easier to expose as a subdir than to add a new DNS hostname.

**Comment by joshperry** [comment]
I guess so! #199

**Comment by ashutoshvct** [comment]
Doesn't work for me. The page breaks, the URL is redirecting to public folder not the subfolder/public. What do I need to change? 
I have changed the nginx proxy settings. I have give the /subdirectory/ in the base url path of config.js.
Please help me out here.

**Comment by wulfsolter** [comment]
@ashutoshvct Change `config.site.baseUrl` and read https://nginx.org/en/docs/

**Comment by ashutoshvct** [comment]
@wulfsolter I have changed it from '/' to '/subdirectory'.

**Comment by ashutoshvct** [comment]
@wulfsolter It worked for me. Sorry, I had started the application as daemon and I was restarting nginx, not mongo-express. 
This was one of the silly mistake made by me.

**Comment by vicatcu** [comment]
Just wanted to share my experience here. In order to make it work, I had to have an Nginx entry that looked like this:
```
location /mongo/ {
   proxy_pass http://localhost:8081/;
}
```

... then I made my config.js have `site.baseUrl = '/mongo/'`

... then in app.js I did:
```
app.use('/', middleware(config));
app.use('/', csrf());
```

... then in views/layout.html I did:
```
<base href="/mongo/">
...
window.ME_SETTINGS = {
...
  baseHref: '/mongo/', // not sure if this change was needed
...
};
```

... and finally in all the html files in the views folder I removed all the {{ baseHref }} remaining strings (replaced with empty string). Presto.

Feels like that should have been easier... but at any rate I hope this is helpful to someone else someday :)

**Comment by joshperry** [comment]
@vicatcu I believe your issue is with the trailing slash in your location block.

My nginx config looks like this:

		location /mongoadmin {
			proxy_pass		http://mongo-express:8081;
			proxy_set_header	Host		$host;
			proxy_set_header	X-Real_IP	$remote_addr;
		}

The only other config I do is to set environment variable `ME_CONFIG_SITE_BASEURL=/mongoadmin`.

**Comment by vicatcu** [comment]
@joshperry cool that sounds _a lot_ cleaner :+1:

**Comment by vicatcu** [comment]
@dozoisch related #348... can you spot what's wrong with this Apache configuration analogy?

```
   <Location /mongo>
      ProxyPass http://127.0.0.1:8081
      ProxyPassReverse http://1127.0.0.1:8081
   </Location>
```

**Comment by pacalyps23** [comment]
> @vicatcu I believe your issue is with the trailing slash in your location block.
> 
> My nginx config looks like this:
> 
> ```
> 	location /mongoadmin {
> 		proxy_pass		http://mongo-express:8081;
> 		proxy_set_header	Host		$host;
> 		proxy_set_header	X-Real_IP	$remote_addr;
> 	}
> ```
> 
> The only other config I do is to set environment variable `ME_CONFIG_SITE_BASEURL=/mongoadmin`.

Where does the ME_CONFIG_SITE_BASEURL config go?

**Comment by saqib-pace** [comment]
> > @vicatcu I believe your issue is with the trailing slash in your location block.
> > My nginx config looks like this:
> > ```
> > 	location /mongoadmin {
> > 		proxy_pass		http://mongo-express:8081;
> > 		proxy_set_header	Host		$host;
> > 		proxy_set_header	X-Real_IP	$remote_addr;
> > 	}
> > ```
> > 
> > 
> > The only other config I do is to set environment variable `ME_CONFIG_SITE_BASEURL=/mongoadmin`.
> 
> Where does the ME_CONFIG_SITE_BASEURL config go?

That goes as your os environment variable. If you are using docker, then just this is an environment variable in docker-compose.yaml file.

**Comment by farshadmb** [comment]
> @vicatcu I believe your issue is with the trailing slash in your location block.
> 
> My nginx config looks like this:
> 
> ```
> 	location /mongoadmin {
> 		proxy_pass		http://mongo-express:8081;
> 		proxy_set_header	Host		$host;
> 		proxy_set_header	X-Real_IP	$remote_addr;
> 	}
> ```
> 
> The only other config I do is to set environment variable `ME_CONFIG_SITE_BASEURL=/mongoadmin`.

@joshperry 
What the config would be when we use `Traefik` as a reverse proxy?

I've used both trailing and leading slash. but the routing problem is exist. 

`ME_CONFIG_SITE_BASEURL=/mongoadmin` or `ME_CONFIG_SITE_BASEURL=/mongoadmin/`

```Docker-compose
- "traefik.http.routers.mongo-express.rule=Host(`domain.com`) && (PathPrefix(`/mongoadmin`) || PathPrefix(`//mongoadmin/`))"
- "traefik.http.routers.mongo-express.entrypoints=web"
- "traefik.http.routers.mongo-express.middlewares=mongo-express"
- "traefik.http.middlewares.mongo-express.stripprefix.prefixes=${MONGO_EXPRESS_PATH},/${MONGO_EXPRESS_PATH}"
- "traefik.http.middlewares.mongo-express.stripprefix.forceslash=true"
```
