### ISSUE TITLE
Big document on mongo 3.2 failes

### ISSUE THREAD

**Issue by egut** [andzdroid/mongo-express#147]
Hi 

I'm using mongo-express (https://hub.docker.com/r/knickers/mongo-express/) and with big documents in mongo it fails with error "topology was destroyed", for small documents it fine. With big documents I mean like a 1MB of json.

When switching to mongo:3.0.7 the both big and small documents work just fine. (Yes I have a docker-compose file and a fixture so the setup is consistent.)

/BR Erik

**Comment by wulfsolter** [comment]
It could be a timeout issue? See https://stackoverflow.com/questions/30425739/mongolab-nodejs-topology-destroyed

So you could try setting the keepAlive and/or connectTimeoutMS as per "Individual Server Level Options" in https://mongodb.github.io/node-mongodb-native/2.0/reference/connecting/connection-settings/

The relevant lines to add the settings are in https://github.com/andzdroid/mongo-express/blob/master/db.js#L11-L14

If you could have a quick play, and let us know what the solution is we could add it to the config.

**Comment by wulfsolter** [comment]
changed the default requestSizeLimit to 50mb, please re-open and let me know if issue persists :)

https://github.com/andzdroid/mongo-express/commit/a9a5430a6f56f7d4d7a6d671283ec1a0aa8a3ba8
