### ISSUE TITLE
Login for default mongodb installation with no authentication

### ISSUE THREAD

**Issue by babnik63** [andzdroid/mongo-express#149]
I have Installed MongoDB with no authentication enabled. so when I open mydomain:8081 It asks for login, so what should I enter for credential?

**Comment by wulfsolter** [comment]
Default credentials for basicAuth are admin:pass but it is highly recommended you change these by copying the `config.default.js` file to `config.js` and adjusting the relevant lines.

https://github.com/andzdroid/mongo-express/commit/c418318d58db9e2025d899f1e9c1798e1448a048
