### ISSUE TITLE
Need a TABLE view

### ISSUE THREAD

**Issue by keel** [andzdroid/mongo-express#150]
That's very  important for me.

**Comment by wulfsolter** [comment]
Could you please explain by what you mean with a "TABLE view"?

**Comment by keel** [comment]
I mean the query results showing as a table, like RoboMongo's "View results in table mode".
so you don't need to click to expand every data.

**Comment by wulfsolter** [comment]
https://github.com/andzdroid/mongo-express/commit/4863e638b936d9ae422cfcd66eed62b7af7584e5

**Comment by keel** [comment]
That's so Cool! Thank you very much!
