### ISSUE TITLE
Server not loading my config.js

### ISSUE THREAD

**Issue by saraht129** [andzdroid/mongo-express#151]
I made a copy of config.default.js into a file named config.js and applied my configurations into it, and when I start mongo express `mongo-express -u username -p password -d database` (I installed mongo express globally), the server doesn't seem to load my configurations. There are no warnings or whatsoever to tell me what might have gone wrong. I'm seeing the red warning `"basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!"` every single time.

**Comment by wulfsolter** [comment]
When passing command line params it will override config.js params. 

Starting with just `$ mongo-express` will load your custom config.js

**Comment by saraht129** [comment]
I tried starting it up with just `$ mongo-express`, it's still loading the default config. What could be the issue here? The configs I edited in my config.js are as below:

`auth`, `adminUsername`, `adminPassword`, `basicAuth` and `defaultKeyNames`.

**Comment by wulfsolter** [comment]
There's nothing else going on - see https://github.com/andzdroid/mongo-express/blob/master/app.js#L17-L21 - tries loading `config.js`, if that fails, loads `config.default.js`.

Maybe insert a `console.log(e)` between lines 19 & 20 to see *why* loading `config.js` fails. I would be interested to see what the cause is, if we can help prevent this in future.

**Comment by saraht129** [comment]
Thanks for the tips! @wulfsolter 
It turns out to be a syntax error on my `config.js`. It would be helpful if you can include the log whenever the custom config fails to load. 

Cheers.

**Comment by wulfsolter** [comment]
Added logging if parsing `config.js` fails https://github.com/andzdroid/mongo-express/commit/53d688ee4477fb389f4a2f81647e583b10811f9c
