### ISSUE TITLE
Install failed after "Querying vulnerabilities database..."

### ISSUE THREAD

**Issue by homkai** [andzdroid/mongo-express#154]
Install failed after "Querying vulnerabilities database..."
Here the log is:

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "snyk-protect"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! mongo-express@0.29.5 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mongo-express@0.29.5 snyk-protect script 'snyk protect'.

**Comment by homkai** [comment]
The error is occured when npm install -g.
I had run the powershell as administrator

**Comment by wulfsolter** [comment]
Snyk has now been removed as dependency, forgot to update npm
