### ISSUE TITLE
Connect to databases without credentials

### ISSUE THREAD

**Issue by knickers** [andzdroid/mongo-express#158]
The new default auth object doesn't work the same way it used to. How can I set the new VCAP_SERVICES environment variable to disable the username and password?

**Comment by knickers** [comment]
Or, what would be the best way to set values in the mongo object from the command line?

**Comment by knickers** [comment]
In case I was too vague before, I'm talking about the mongo object on lines 20 - 27 and the auth object on lines 53 - 57 in config.default.js

**Comment by knickers** [comment]
My real problem didn't really have anything to do with all the previous comments, I just needed to turn on administrator access :stuck_out_tongue_winking_eye:.

**Comment by aemonge** [comment]
I can't connect without credentials. Do you have a fix for it ?

**Comment by dozoisch** [comment]
@aemonge can't really help without any error or anything.
