### ISSUE TITLE
is empty for

### ISSUE THREAD

**Issue by LeandroFavero** [andzdroid/mongo-express#161]
Hi,

First: Congratulations for your great tool!!!

Second: I just update mongo-express, using like a middleware with node 4.2.4 LTS (tested with 5.4.0 too) and boolean fields with false, appears the message "is empty for".
Create this document:
{
    "_id": 2,
    "name": "Administrator",
    "password": "a9f266sjdjai290s78153833c1b77cff07bd5f53b0",
    "blocked": false
}

Field blocked will show: blocked is empty for

**Comment by wulfsolter** [comment]
Thanks for providing a working example :) 

Fixed with https://github.com/andzdroid/mongo-express/commit/bc05ecef359bd79d0bfbbf63765ed0f2bbb70620
