### ISSUE TITLE
Does not work on Debian 8

### ISSUE THREAD

**Issue by meepeek** [andzdroid/mongo-express#164]
OS - Debian 8
Node version - 4.2.4
NPM version - 2.14.12
running npm -g install mongo-express result as follow:

[root:/home/thee]# npm install -g mongo-express
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
\
> kerberos@0.0.17 install /home/thee/nodejs/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/thee/nodejs/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/kerberos/.node-gyp"
make: Entering directory '/home/thee/nodejs/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/home/thee/nodejs/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/thee/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/home/thee/nodejs/bin/node" "/home/thee/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/thee/nodejs/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/kerberos
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
/home/thee/nodejs/bin/mongo-express -> /home/thee/nodejs/lib/node_modules/mongo-express/app.js
mongo-express@0.29.14 /home/thee/nodejs/lib/node_modules/mongo-express
├── basic-auth-connect@1.0.0
├── underscore@1.8.3
├── async@1.5.2
├── cookie-parser@1.4.0 (cookie-signature@1.0.6, cookie@0.2.2)
├── serve-favicon@2.3.0 (fresh@0.3.0, etag@1.7.0, ms@0.7.1, parseurl@1.3.0)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── method-override@2.3.5 (methods@1.1.1, vary@1.0.1, parseurl@1.3.0, debug@2.2.0)
├── morgan@1.6.1 (on-headers@1.0.1, basic-auth@1.0.3, depd@1.0.1, on-finished@2.3.0, debug@2.2.0)
├── express-session@1.11.3 (cookie@0.1.3, cookie-signature@1.0.6, utils-merge@1.0.0, on-headers@1.0.1, parseurl@1.3.0, depd@1.0.1, crc@
3.3.0, uid-safe@2.0.0, debug@2.2.0)
├── errorhandler@1.4.2 (escape-html@1.0.2, accepts@1.2.13)
├── body-parser@1.14.2 (content-type@1.0.1, bytes@2.2.0, depd@1.1.0, qs@5.2.0, on-finished@2.3.0, raw-body@2.1.5, http-errors@1.3.1, de
bug@2.2.0, iconv-lite@0.4.13, type-is@1.6.10)
├── express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, cookie@0.1.3, array-flatten@1.1.1, cookie-signature@1.0.6, utils-merge@
1.0.0, methods@1.1.1, vary@1.0.1, content-type@1.0.1, etag@1.7.0, fresh@0.3.0, content-disposition@0.5.0, range-parser@1.0.3, path-to-r
egexp@0.1.7, serve-static@1.10.0, parseurl@1.3.0, depd@1.0.1, qs@4.0.0, on-finished@2.3.0, finalhandler@0.4.0, debug@2.2.0, proxy-addr@
1.0.10, type-is@1.6.10, accepts@1.2.13, send@0.13.0)
├── consolidate@0.13.1 (bluebird@2.10.2)
├── swig@1.4.2 (optimist@0.6.1, uglify-js@2.4.24)
├── cli-color@1.1.0 (ansi-regex@2.0.0, d@0.1.1, timers-ext@0.1.0, es6-iterator@2.0.0, memoizee@0.3.9, es5-ext@0.10.11)
└── mongodb@2.1.4 (es6-promise@3.0.2, readable-stream@1.0.31, kerberos@0.0.17, mongodb-core@1.2.32)
[root:/home/thee]# mongo-express
zsh: command not found: mongo-express
[root:~thee]# 
[root:~thee]#

**Comment by micooz** [comment]
Maybe you should upgrade your NPM or install build-essential if your haven't installed it before.

**Comment by meepeek** [comment]
Thanks for the reply. It was my mistake, setting up nodejs manually.
