### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by micooz** [andzdroid/mongo-express#166]
when start in a docker container:

> /app/app.js:5
> const clc             = require('cli-color');
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:501:10)
>     at startup (node.js:129:16)
>     at node.js:814:3

**Comment by wulfsolter** [comment]
Sounds like an old version of Node.

Can you update the version? A quick google suggests changing the top line of `Dockerfile` to
`FROM node:5.4.1-slim`

Let me know if that works @micooz

**Comment by wulfsolter** [comment]
Fixed https://github.com/andzdroid/mongo-express/commit/ce832c72a00334ee426c54145b8cc2d4bb849f69

**Comment by micooz** [comment]
it works, thanks!

**Comment by wulfsolter** [comment]
If you are seeing this error, please upgrade your version of NodeJS to something that is currently still officially supported.
