### ISSUE TITLE
0.30.4 release problems

### ISSUE THREAD

**Issue by k2s** [andzdroid/mongo-express#170]
there is release 0.30.4 here https://www.npmjs.com/package/mongo-express
1. but there is no such tag in git repository
2. middleware.js is missing in it and also in master branch

**Comment by wulfsolter** [comment]
Please explain what a tag is required?

**Comment by wulfsolter** [comment]
middleware.js is in the lib/ folder. If you feel the documentation is not clear enough, a PR would be most welcome.

**Comment by k2s** [comment]
1. I don't say it is required, but it was common before and makes it easier to track changes in npm package
2. thanks for the tip. PR seams not to be needed anymore because it is correct in README.md now

thank you
