### ISSUE TITLE
Limit sub-object height in collection view

### ISSUE THREAD

**Issue by knickers** [andzdroid/mongo-express#175]
The data-set I'm working with has some documents with large objects inside that makes the collections page really long to scroll through. So I've added a 5 line limit in the [`to_display` function](https://github.com/andzdroid/mongo-express/blob/220e12de6b7d4d60b58d372d8fc90f47ee551c87/lib/filters.js#L121). My question is, will this break gridfs views? I can see that gridfs also calls this function, but I don't have any gridfs data to test and see what it looks like.

**Comment by wulfsolter** [comment]
Cross over with https://github.com/andzdroid/mongo-express/issues/176 maybe? 

@bkabrda's suggestion seems a pretty good start

**Comment by wulfsolter** [comment]
@knickers does this fix from @bkabrda work for you? https://github.com/andzdroid/mongo-express/pull/178

**Comment by knickers** [comment]
Yes :smile: I might poke around and make it a little more efficient if that's OK :wink:

**Comment by wulfsolter** [comment]
Appreciated!
