### ISSUE TITLE
Dynamic collapsing of subobjects

### ISSUE THREAD

**Issue by bkabrda** [andzdroid/mongo-express#176]
Hi, I just wanted to ask whether you could consider implementing collapsing subobjects in collection views. I have some subobjects that are pretty big and setting `maxPropSize` makes them collapsed completely - and when I click them, I see the whole huge subobject and have no way to hide it.
It'd be really cool if there was an option to dynamically (un)collapse the subobjects similar to [1]. I'd be glad to send a PR, but I'm no JS/NodeJS expert. Perhaps given some pointers, I could do that (like - is there actually a library for that? My googling doesn't reveal anything, but perhaps I'm just doing it wrong).

[1] http://jsfiddle.net/t5Hxk/5/

**Comment by wulfsolter** [comment]
I really like the idea of collapsing if object is too big :). I'm not aware of any lib that does it, but the jsfiddle you posted looks like a good direction - handle collapsing on client side.

Maybe we throw in a hook that copypaste still yields original content?

**Comment by bkabrda** [comment]
Ok, I'll try to do some more research and work on this a bit. I'll let you know if I think I'm getting close or if I'm totally lost :)

**Comment by bkabrda** [comment]
Seems like https://github.com/caldwell/renderjson could do the job (live demo at http://caldwell.github.io/renderjson/). I'll try experimenting with it to see if it would fit into mongo-express.

**Comment by wulfsolter** [comment]
Ooooo, https://github.com/caldwell/renderjson looks very slick! Nice find.
