### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by tatakci** [andzdroid/mongo-express#179]
it always crashes need to get restarted after some usage not sure why here are the logs

> <--- Last few GCs --->
> 
> 151553499 ms: Mark-sweep 1397.4 (1455.7) -> 1397.4 (1455.7) MB, 878.5 / 0 ms [allocation failure] [GC in old space requested].
> 151554378 ms: Mark-sweep 1397.4 (1455.7) -> 1397.3 (1455.7) MB, 879.1 / 0 ms [allocation failure] [GC in old space requested].
> 151555258 ms: Mark-sweep 1397.3 (1455.7) -> 1397.3 (1455.7) MB, 880.3 / 0 ms [last resort gc].
> 151556140 ms: Mark-sweep 1397.3 (1455.7) -> 1397.3 (1455.7) MB, 881.2 / 0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x5e344e37339 <JS Object>
>     1: /* anonymous */(aka /* anonymous */) [/usr/lib/node_modules/mongo-express/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/lib/bson/parser/deserializer.js:82] [pc=0x1de88800de32] (this=0x5e344e04131 <undefined>,buffer=0x1c4f31dc36c1 <an Uint8Array with map 0xf771500f7e1>,index=31735,options=0x1c4f31dc3791 <an Object with map 0x39eca1dec289>,isArray=0x5e344e04431 <false>)
>  ...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
> Aborted (core dumped)
>

**Comment by wulfsolter** [comment]
Looks like your system is running out of memory when trying to fetch from Mongo

By default node has a pretty high limit before garbage collection kicks in, often higher than the available memory on a tiny server - https://github.com/nodejs/node-v0.x-archive/wiki/FAQ#what-is-the-memory-limit-on-a-node-process - so maybe something like https://stackoverflow.com/questions/7193959/memory-limit-in-node-js-and-chrome-v8 could help.
