### ISSUE TITLE
XSS Injection in result display area

### ISSUE THREAD

**Issue by mmis1000** [andzdroid/mongo-express#180]
![xss](http://puu.sh/naaRa/be9986170b.png)
the cute_penda tag is caused by xss

**Comment by wulfsolter** [comment]
XSS?

**Comment by mmis1000** [comment]
yes, the selected text should be displayed as 
`<cute_penda>: ubuntu的說面環境好頓QAQ`
bug i actully got
`: ubuntu的說面環境好頓QAQ`
the `<cute_penda>` was though as a html tag intead enscaped to `&lt;cute_penda&gt;`
it is apparently a xss injection problem

**Comment by wulfsolter** [comment]
Ah. Not XSS, but yes document isn't escaped properly and thus getting processed by the browser's render engine.

Fixed with https://github.com/andzdroid/mongo-express/commit/bac47eceaf6bf6602dd9995f96a80da223fde1bf
