### ISSUE TITLE
delete document

### ISSUE THREAD

**Issue by bote795** [andzdroid/mongo-express#182]
I am not sure if this only for me or in general, but when I try to use the delete button  (red trash in a collection) to delete a document. It doesn't delete the correct document. It seems it might be just deleting the top one. 
But if you go to edit document by clicking on it then delete. It deletes the correct one.

**Comment by wulfsolter** [comment]
Thanks @bote795! Fixed with https://github.com/andzdroid/mongo-express/commit/12dff1914cb1fe007a474c38514eee0e9b7cd448
