### ISSUE TITLE
Cannot view/delete item if its _id is not an ObjectId

### ISSUE THREAD

**Issue by marshallswain** [andzdroid/mongo-express#23]
Right now view/delete require the _id to contain a full ObjectId.  It would be nice to provide support for scenarios that do not use an ObjectId, such as when using connect-mongo for sessions in a project.  connect-mongo uses a 24-digit string, but not a full ObjectId.

**Comment by wZVanG** [comment]
If you have an auto-incremented field error occurs because the id is a string

Find in **/app.js**:
```javascript
 if (id.length == 24) {
    //Convert id string to mongodb object ID
    try {
      id = new mongodb.ObjectID.createFromHexString(id);
    } catch (err) {
    }
  }
```

Add after: **else** condition
```javascript
else{
    id = /^[1-9]+[0-9]*$/.test(id) ? +id : id
  }
```

**Comment by wulfsolter** [comment]
https://github.com/andzdroid/mongo-express/commit/a35c26ab8852344dfc15b2dc5db5924259ddd861
