### ISSUE TITLE
collection list can not update when add a collection use mongo shell or other program

### ISSUE THREAD

**Issue by zenany** [andzdroid/mongo-express#34]
when i create a collection with mongo shell, the collection cannot find in the page /db/{database_name}.
in order to mangement the collection created by mongo shell, i need to restart mongo-express. 
it seems that server cache the collection names for every databse.

**Comment by DavidePastore** [comment]
:+1:

**Comment by Petah** [comment]
+1

**Comment by leepowellcouk** [comment]
+1

**Comment by aa21** [comment]
+1 

A database management control panel that doesn't reflect changes to collections is ***incomplete***. At the very least there should be a "reload" button. Better if it updates on browser refresh.

**Comment by wulfsolter** [comment]
Thanks for your feedback @aa21 . A few hours prior to your post I had merged https://github.com/andzdroid/mongo-express/pull/69 from @svarlamov to include a refresh button, so before jumping on threads and posting negativity **in bold** please update to latest version.

@DavidePastore had written code to refresh databases a while back, but by the time I discovered this project and gained write access the code has diverged quite a bit and the old PR doesn't fit in anymore. https://github.com/andzdroid/mongo-express/pull/50

If you would like to submit a PR of code that does it automatically on page load, ideally with tests, then we would welcome it. @DavidePastore was on the right track, his PR seems pretty straightforward  :)

**Comment by aa21** [comment]
Thanks for your reply @wulfsolter. I'll update and let you know how it goes for me.

**Comment by wulfsolter** [comment]
Unsure why your custom config.js was deleted, seems rather bizarre. The rest of changes were as expected as we trialled "readOnly: true" as default.
