### ISSUE TITLE
Add cli

### ISSUE THREAD

**Issue by adius** [andzdroid/mongo-express#56]
You should add a command line interface so that the server can be easily started without having to explicitly run the javascript file!

**Comment by cappslock** [comment]
+1. Maybe add a binary if installed globally?

**Comment by nielsdebruin** [comment]
+1 Mabye something like redis-commander has.

**Comment by ambrosechua** [comment]
Take a look at [this branch](https://github.com/ambrosechua/mongo-express/tree/patch-4) of my fork, it's still messy so feel free to clean it up!

**Comment by h2non** [comment]
+1 

@ambrosechua You can use `yargs` or `commander.js` for a better approach creating a CLI

**Comment by wulfsolter** [comment]
Merged in @ambrosechua's work with https://github.com/andzdroid/mongo-express/commit/68ddc761ab17f5b2065e1c98ddd268e910cc89e6
