### ISSUE TITLE
A question for the moderators!

### ISSUE THREAD

**Issue by karthik25** [andzdroid/mongo-express#59]
Hello!

Was just wondering if the pull requests are going to be merged! Is this project not being managed by anybody? I feel like it has a lot of potential and would hate to see it not being active!

Thanks!

**Comment by karthik25** [comment]
Thanks @andzdroid for accepting my pull requests! Next task in my agenda is to change the status of mongo-express (from inactive to active) in http://mongodb-tools.com!

**Comment by andzdroid** [comment]
Thanks for your contributions, @karthik25!
