### ISSUE TITLE
Invalid filter to_string

### ISSUE THREAD

**Issue by bassemlhm** [andzdroid/mongo-express#60]
When clicking VIEW on any collection, I get : 
500 Error: Invalid filter "to_string" on line 178 in file /var/www/ArtBud/artbangbang/node_modules/mongo-express/views/collection.html.

Likely cause : connect-mongo stores its data as strings, rather than as embedded documents.
http://stackoverflow.com/questions/13113312/mongo-express-doesnt-correctly-display-embedded-documents

**Comment by Evanlec** [comment]
I get this error also -- surprised no one else has had this?

**Comment by travispence** [comment]
I resolved this issue by changing the `swig` dependency in the  `package.json` to be
```
{
  ...
 "swig": "^1.3.2",
}
```

Then running 'npm update`

**Comment by Evanlec** [comment]
That worked, updating swig to latest (1.4.2), thank you!

**Comment by wulfsolter** [comment]
Updated https://github.com/andzdroid/mongo-express/commit/b23dd6bc473684088f9631acfef941fb99f69385 and published to npm

**Comment by cbweaver** [comment]
I receive a similar error:  "TypeError: Cannot call method 'toString' of undefined at Object.exports.to_string (/home/vagrant/app/node_modules/mongo-express/filters.js).

I am attempting to display a value from an embedded document as a defaultKeyName, as shown below:

```javascript
...
defaultKeyNames: {
  "gardendb": { // my database name
    "plants": "name.scientific" // collection (plants): field (name.scientific)
    //"plants": "sciName" // Works as you would expect, but this isn't how I would prefer to structure my document.
  }
}
```

The schema for Plants is:

```javascript
var PlantSchema = new Schema({
  name: {
    common: [String],
    scientific: String
  }
});
```

A document in `gardendb` looks like:

```javascript
{
  "_id": ObjectID("564a15d9b14c2c705899969e"),
  "name": {
    common: [
      "Lettuce"
    ],
    scientific: "Lactuca sativa"
  },
  "sciName": "Lactuca sativa"
}
```

Setting defaultKeyNames to use the `sciName` field shows "Lactuca sativa" in the table as you would expect. Is is not possible to list the embedded document value for `name.scientific` in the table? I have confirmed my version of `swig` within mongo-express is 1.4.2. My version of mongo-express is 0.26.0.

**Comment by cbweaver** [comment]
I discovered the error I was getting wasn't actually an error. mongo-express was working as intended. The existing collections.html file doesn't support embedded documents. Here's my solution to add that functionality:

views/collection.html
```
...
<a class="accordian-toggle" data-toggle="collapse" data-parent="_accordian" href="#body_{{ loop.index}}">
  {% if document[defaultKey] == "" %}
    {{defaultKey}} is empty for {{document["_id"]|to_string}}
  {% else %}
    {% if !document[defaultKey] %}
      {% if defaultKey|is_embeddedDocumentNotation %}
        {{edKey(document, defaultKey)}}
      {% else %}
        {{defaultKey}} is undefined for {{document["_id"]|to_string}}
      {% endif %}
    {% else %}
      {{document[defaultKey] |to_string}}
    {% endif %}
  {% endif %}
</a>
...
```

routes/collection.js
```javascript
...
var collectionName = req.params.collection;
var defaultKey = (config.defaultKeyNames && config.defaultKeyNames[dbName] && config.defaultKeyNames[dbName][collectionName]) ?
      config.defaultKeyNames[dbName][collectionName] :
      '_id';
var edKey = function (doc, defaultKey) {
  var defaultKeyAsArray = defaultKey.split('.');
  var val = doc;
  for (var i = 0; i < defaultKeyAsArray.length; i++) {
    if (val[defaultKeyAsArray[i]]) {
      val = val[defaultKeyAsArray[i]];
    }
  }
  return val;
};

...

var ctx = {
  ... 
  defaultKey: defaultKey,
  edKey: edKey
};
```

filters.js
```javascript
...
exports.is_embeddedDocumentNotation = function (input) {
  return /^(?:[a-zA-Z0-9_]+\.)+[a-zA-Z0-9_]+/.test(input);
}
```

**Comment by wulfsolter** [comment]
@cbweaver: If you submit your code as a Pull Request (fork, do code, commit, pull request) then you get credited with your contributions on GitHub http://readwrite.com/2014/07/02/github-pull-request-etiquette

**Comment by wulfsolter** [comment]
Thanks for the PR @cbweaver
