### ISSUE TITLE
mongoDB version compatibility 

### ISSUE THREAD

**Issue by chrifmarwen** [andzdroid/mongo-express#63]
I wat to add a document but it says :
"Something went wrong: MongoError: driver is incompatible with this server version"

Recent version not supported yet ?

**Comment by 123marvin123** [comment]
Got the same error with mongodb 3.0.2

**Comment by ambrosechua** [comment]
#61 fixes this issue you can try it first.

**Comment by 123marvin123** [comment]
It works good, I was waiting for this, thank you :+1:

**Comment by simllll** [comment]
Thanks :) worked also for me

**Comment by pkwenda** [comment]
我也遇到同样的问题了：
 [initandlisten] db version v3.2.6
 "mongodb": "^1.3.23"

**Comment by wulfsolter** [comment]
@pkwenda Can you clarify please?
