### ISSUE TITLE
ISODate format output bug

### ISSUE THREAD

**Issue by fbukevin** [andzdroid/mongo-express#64]
I stored some crawled data in mongodb and there is a field "created" which value format looks like this in mongo-express：

![bug](https://cloud.githubusercontent.com/assets/4548874/7730273/e2fb7e9e-ff4b-11e4-9a41-26b2fcb868d7.JPG)

It looks fine, but when I tend to export it to JSON file, there appears a character error：
![export](https://cloud.githubusercontent.com/assets/4548874/7730303/1aacdea0-ff4c-11e4-90a1-9c98b5e10d31.JPG)

**Comment by wulfsolter** [comment]
Closing as inactive
