### ISSUE TITLE
AuthenticationFailed MONGODB-CR credentials missing in the user document

### ISSUE THREAD

**Issue by chuank** [andzdroid/mongo-express#67]
I'm trying out a single MongoDB instance on my server and using Mongo 3.0.3 to set up.

`mongo-express` couldn't seem to authenticate any of my users – **admin** or **otherwise** – I've checked the instructions in **config.js** and followed them, but I'm not getting any further beyond an empty mongo-express homepage. Attempting to click on the listed databases (which I've populated using the auth array) crashes mongo-express.

The error log from `mongo-express` as it starts up reads:
```
{ [MongoError: auth failed] name: 'MongoError', ok: 0, errmsg: 'auth failed', code: 18 } mongo-express-0 (err): Could not authenticate to database "dbname"
```
Cross-referencing the `mongod` logs revealed this error:
    AuthenticationFailed MONGODB-CR credentials missing in the user document

Am I totally missing something in my configuration? I've tried all manner of user types in `config.js`:
* `root` superuser, created in the admin db, declared in `adminUserName/adminPassword`
* `dbOwner` poweruser, created in my db, declared in `auth` array
* `readWrite` regular user, created in my db, declared in `auth` array

I have absolutely no issues in accessing my mongodb instance, authenticating and traversing different databases via **mongoshell**, which is why I'm hoping someone here can help me out. Thanks for reading~

**Comment by Morras** [comment]
The problem seems to arise from the fact that Mongo 3.0 switched away from using MONGODB-CR credentials for user authentication [reference](http://docs.mongodb.org/manual/core/authentication/#authentication-mongodb-cr) .
I have just had the same problem and managed to solve it by the help of [this thred](https://jira.mongodb.org/browse/SERVER-17459).
This is my first mongo installation so I do not know alot about it, but this solved it for me.

**Comment by matteocontrini** [comment]
@Morras what is exactly the procedure that helped you solve this issue? Thanks

**Comment by Morras** [comment]
@matteocontrini  I followed Jose Luis Pedrosas  [3 steps](https://jira.mongodb.org/browse/SERVER-17459?focusedCommentId=842843&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-842843)

**Comment by wulfsolter** [comment]
Closing as inactive
