### ISSUE TITLE
No option to create new databases

### ISSUE THREAD

**Issue by zwarag** [andzdroid/mongo-express#68]
I think I set up mongo wrong or something.
I'm a beginner tho.

When I login into mongo-express, I cannot create databases, even tho I it authenticates against a root-role user.

![screenshot](http://i.imgur.com/dspdwYU.png)

**Comment by ambrosechua** [comment]
It has not been implemented yet. Check out http://www.tutorialspoint.com/mongodb/mongodb_create_database.htm

**Comment by wulfsolter** [comment]
Closed thanks to @muxahuk
