### ISSUE TITLE
Replica Set Support

### ISSUE THREAD

**Issue by nodesocket** [andzdroid/mongo-express#78]
Are replica set connections still not supported?

**Comment by maxpmaxp** [comment]
Any update on that?

**Comment by paton** [comment]
Patch for replica support here:

https://github.com/paton/mongo-express/commit/b620874d858724103760f3424adc616367e70169

**Comment by wulfsolter** [comment]
Merged https://github.com/andzdroid/mongo-express/commit/52d45891e2be05443b1bc5f887784eebe1806871 into master and published to npm
