### ISSUE TITLE
updating a record breaks mongodb query for other open mongodb connections in node server

### ISSUE THREAD

**Issue by mehuleo** [andzdroid/mongo-express#80]
I have a node server with an open mongodb connection for the life time of the server. Now if I update some record in some collection using mongo-express, my nodejs server's already open mongodb connection fails to query that collection. After that I tried to update other record in same collection using mongo-express, and mongo-express failed to update record and showed me 'That document is not valid!' error.

**Comment by wulfsolter** [comment]
Closing as inactive
