### ISSUE TITLE
advanced query example

### ISSUE THREAD

**Issue by limulidae** [andzdroid/mongo-express#81]
I don't know how to use your Advanced -> Query/Fields
could you give me an example??

**Comment by kford** [comment]
Same here.. Trying to setup an object as Mongo expects for the projection but it doesn't seem to have any effect.

**Comment by MarkusPint** [comment]
+1

**Comment by kford** [comment]
So it was just as you'd expect, like a basic mongo query with a fields object, which I tried before posting this issue.  I'm not sure why it didn't work, but see my screenshot for an [contrived] example of it working.

![selection_001](https://cloud.githubusercontent.com/assets/821268/8731778/64a74f16-2bae-11e5-9ea6-411382dcbc6d.png)

**Comment by Alttaf** [comment]
+1

**Comment by linkpark182** [comment]
+1

**Comment by wulfsolter** [comment]
PRs are welcome @linkpark182 

The "advanced" search passes query & fields params directly on to db.collection.find(query, fields...) https://github.com/mongo-express/mongo-express/blob/master/lib/routes/collection.js#L72-L86

For instructions on how to use MongoDB, see the manual. https://docs.mongodb.org/manual/reference/method/db.collection.find/

**Comment by hackerunet** [comment]
is possible to run an aggregate query in advance mode without using projection? I want to have full control of the queries created as a mongo client in a console.

**Comment by avico78** [comment]
can some1 provide an example of how to use the search advanced? I tried simple stuff like :
  {_id: '605b1844e2bbb42aa22712a7' } or {'field_name' : 'dsdsad123' } ... couldn't figure our how to use it.. actually seems many people asking little guidance for how to use it
