### ISSUE TITLE
No databases showing

### ISSUE THREAD

**Issue by Whitebeard86** [andzdroid/mongo-express#90]
Hello,

I've been able to successfully run the mongo-express app (it also says in the console "database connected"). Although, when I open the web page it only appears the right column statistics, the side bar contains no items / database.

Why could that be?

Thanks,
J.

**Comment by GreenPioneer** [comment]
First things first try updating your swig
```
{
 "swig": "^1.4.2",
}
```
See if that helps any cause it was causing me problems and updating fixed it for me
*** https://github.com/andzdroid/mongo-express/issues/60

**Comment by sunsided** [comment]
Fixed the problem for me as well, however no collections show up when running against MongoDB 3.1.7.

**Comment by tinamore** [comment]
I has same problem. I must create new teamp collection and delete it then list collections show. Please fix.

**Comment by wulfsolter** [comment]
Updated https://github.com/andzdroid/mongo-express/commit/b23dd6bc473684088f9631acfef941fb99f69385 and published to npm
