### ISSUE TITLE
Apple app rejected because of node.js and mongo

### ISSUE THREAD

**Issue by NileshBadgi-Idealtechnologys** [andzdroid/mongo-express#91]
I have submitted app more than 5 times because of node.js and mongodb, Apple review always giving me error of could not connect to server, Can you let me know is there is any issue with that codes,

**Comment by karthik25** [comment]
You may have to elaborate more to elicit any kind of response! Do you mean your app connects to a node app which connects to a mongo server? What happens if you try to access your node app through a desktop browser?

**Comment by wulfsolter** [comment]
Unrelated to mongo-express, closing.
