### ISSUE TITLE
empty collection on mongo 3.1

### ISSUE THREAD

**Issue by mhf-ir** [andzdroid/mongo-express#95]
There is no collection shown on mongodb 3.1

**Comment by DavidePastore** [comment]
+1

**Comment by evseevnn** [comment]
+1

**Comment by wulfsolter** [comment]
PRs are much more welcome than +1s.....

A bit hard for me to diagnose as I'm running 2.4.5 stable.

**Comment by SL11223344** [comment]
Have same issue - can't see the db's list at all. 
Ready to provide the screenshots or other necessary data.

Mongo ver is 3.1.7 and the collections do exist on db. I've tried different variations at defaultKeyNames - zero luck. Even local:{}  is not displayed. 

![image](https://cloud.githubusercontent.com/assets/13402912/11472818/c5b0589a-9777-11e5-8784-638c968cc0ab.png)

**Comment by wulfsolter** [comment]
@SL11223344 A PR?

**Comment by catorda** [comment]
I see this also, and I'm using MongoDB 3.2

**Comment by wulfsolter** [comment]
@catorda Fancy submitting a pull request?

**Comment by wulfsolter** [comment]
@catorda has done an awesome fix :) Many thanks!

Latest version on npm now handles Mongo 3.x
