### ISSUE TITLE
Deleting a document with the _id field set to null deletes the collection

### ISSUE THREAD

**Issue by UCIS** [andzdroid/mongo-express#96]
Attempting to delete a document which has the _id field set to null using the delete button (X), results in the entire collection being deleted without any warning. This is obviously not the desired behavior and seems to be a result of the assumption that a document has a non-empty _id, which is then used to construct the URL for the delete request.

The frontend should either check for such unexpected values and warn the user, or encode them in some other way that does not result in the entire collection being deleted.

**Comment by wulfsolter** [comment]
Would you like to submit a PR?

**Comment by wulfsolter** [comment]
@UCIS Related? https://docs.mongodb.org/manual/reference/operator/aggregation/group/

**Comment by UCIS** [comment]
I don't think that's directly related. I had a document with the _id field set to null (which was caused by a malfunctioning PHP script, but is technically a valid key). This resulted in a DELETE request for /collection/ (instead of /collection/id-string) when clicking the delete button (X) for the record. This in turn deleted the entire collection.

Unfortunately I don't have time to write a proper patch at the moment, but I will consider doing so when time permits.

**Comment by wulfsolter** [comment]
Fixed with https://github.com/andzdroid/mongo-express/commit/b89ebb8e6b6d848a009564a2d90055f9dd09b44b
