### ISSUE TITLE
npm install mongo-express is different than github sources.

### ISSUE THREAD

**Issue by thomasleduc** [andzdroid/mongo-express#97]
After install directly on my dev server with `npm install mongo-express`, I have some issue to install it automatically with ansible because of the git module.
`git clone` files are not the same than the `npm install` ones and present many errors.

**Comment by wulfsolter** [comment]
@andzdroid

**Comment by thomasleduc** [comment]
That means ?

**Comment by etal2** [comment]
same problem here, also the code (from npm) and documentation don't match

**Comment by etal2** [comment]
I ended up pulling directly from github:
npm install andzdroid/mongo-express
to fix the problem, I guess the npm package is just not updated

**Comment by wulfsolter** [comment]
I've just been given write access to NPM, version bumped and pushed latest.
